### ISSUE TITLE
`message.interaction` gets deprecated in discord.js `14.6.2` for `messageCreateBump` event

### ISSUE THREAD

**Issue by vic1707** [bistro-tech/bartender#42]
<img width="1103" alt="image" src="https://github.com/user-attachments/assets/d8b8c820-5253-44cc-9e59-8d368b5182b7">

**Comment by ThisIsLuckyluck** [comment]
Branche faites pour cette issue.

**Comment by ThisIsLuckyluck** [comment]
![image](https://github.com/user-attachments/assets/8c42baa0-2334-4f72-a2d8-81d993b7d86c)
Qu'est ce que tu en pense vic ?

**Comment by vic1707** [comment]
les définitions de type disent-elles que `commandName` peut exiter ?
as-tu testé ?

**Comment by ThisIsLuckyluck** [comment]
![image](https://github.com/user-attachments/assets/0fea5e3e-7c17-4594-b2e2-78fe2ce2a85f)
Je trouve pas CommandName du coup j'imagine que nan ?

**Comment by vic1707** [comment]
Exact, ça existe pas 🙃
Faut trouver une autre solution
